version: '3.1'
services:
  # civalue_api:
  #     restart: on-failure
  #     container_name: 'civalue_api'
  #     image: civalue_api_java_8
  #     build:
  #       context: '.'
  #       dockerfile: ./docker/app.dockerfile
  #     depends_on:
  #       - civalue_mongo

  #     volumes:
  #       - '.:/opt/project'
  #     ports:
  #       - 3001:3000
        
  # https://hub.docker.com/_/mongo
  civalue_mongo:
    image: library/mongo:4.2
    container_name: civalue_mongo
    restart: always
    ports:
      - "27142:27017"
    volumes:
      - civalue_mongo_local:/data/db

volumes:
  civalue_mongo_local:

networks:
  default:
    name: civalue-dockers-network    